#!/bin/bash
CWD=${BASH_SOURCE%/*}/.git
CDN=https://naciscdn.org/naturalearth/10m/cultural
COUNTRIES=ne_10m_admin_0_countries
STATES=ne_10m_admin_1_states_provinces

cd $CWD; mkdir -p build-data; cd build-data
rm country.json state.json map-data.json 2> /dev/null
set -e

[ -d ${STATES} ] || {
	[ -f ${STATES}.zip ] || curl -O ${CDN}/${STATES}.zip
	unzip -od ${STATES} ${STATES}.zip
}

npx mapshaper -i ${STATES}/${STATES}.shp snap \
	-simplify weighted 20% \
	-rename-layers state \
	-rename-fields code=adm0_a3 \
	-filter-fields code,name \
	-filter 'code === "BRA"' \
	-dissolve code target=state copy-fields=code,name + name=country \
	-o map-data.json format=topojson bbox force target=country,state

# TODO split country states
#[ -d states ] || {
